version: '3.4'

networks:
 stravaclone: 

services:
  stravaclone.db:
   container_name: "stravaclone.db"
   image: mcr.microsoft.com/mssql/server:2022-latest
   ports:
    - 8082:1433
   environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Passw0rd
   networks:
    - stravaclone
  stravaclone.web:
    container_name: "stravaclone.web"
    image: ${DOCKER_REGISTRY-}stravaclone.project
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 3000:8080
    depends_on:
     - stravaclone.db
    networks:
     - stravaclone